<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="author" content="microzz"><link rel="alternative" href="/atom.xml" title="ECUT Club" type="application/atom+xml"><link rel="icon" href="/favicon.png"><title> - ECUT Club</title><link rel="stylesheet" href="/css/main.css"><link rel="stylesheet" href="/js/fancybox/jquery.fancybox.min.css"><!--[if lt IE 9]><script>(function(a,b){a="abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video".split(" ");for(b=a.length-1;b>=0;b--)document.createElement(a[b])})()</script><![endif]--><script src="/js/jquery-3.1.1.min.js"></script><script src="/js/fancybox/jquery.fancybox.min.js"></script><!-- Hotjar Tracking Code for ochukai.me --></head><body style="opacity:0"><header class="head"><h1 class="head-title u-fl"><a href="/">ECUT Club</a></h1><nav class="head-nav u-fr"><ul class="head-nav__list"><li class="head-nav__item"><a href="/archives" class="head-nav__link">カタログ/（目录）</a></li></ul></nav></header><main class="main"><article class="post"><header class="post__head">  <time datetime="2017-04-19T00:24:13.678Z" class="post__time">April 19, 2017</time><h1 class="post__title"><a href="/2017/04/19/promise/"></a></h1><div class="post__main echo"><hr>
<p>title: Promise对象<br>date: 2017-01-14 14:11:38<br>tags:</p>
<ul>
<li>ECMAScript6</li>
<li>JavaScript</li>
<li>JS</li>
<li>ES6</li>
<li>Promise</li>
</ul>
<hr>
<h1 id="Promise对象"><a href="#Promise对象" class="headerlink" title="Promise对象"></a>Promise对象</h1><h2 id="Promise的含义"><a href="#Promise的含义" class="headerlink" title="Promise的含义"></a>Promise的含义</h2><p>Promise是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。它由社区最早提出和实现，ES6将其写进了语言标准，统一了用法，原生提供了<code>Promise</code>对象。</p>
<p>所谓<code>Promise</code>，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果。从语法上说，Promise是一个对象，从它可以获取异步操作的消息。Promise提供统一的API，各种异步操作都可以用同样的方法进行处理。</p>
<p><code>Promise</code>对象有以下两个特点。</p>
<p>（1）对象的状态不受外界影响。<code>Promise</code>对象代表一个异步操作，有三种状态：<code>Pending</code>（进行中）、<code>Resolved</code>（已完成，又称Fulfilled）和<code>Rejected</code>（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。这也是<code>Promise</code>这个名字的由来，它的英语意思就是“承诺”，表示其他手段无法改变。</p>
<p>（2）一旦状态改变，就不会再变，任何时候都可以得到这个结果。<code>Promise</code>对象的状态改变，只有两种可能：从<code>Pending</code>变为<code>Resolved</code>和从<code>Pending</code>变为<code>Rejected</code>。只要这两种情况发生，状态就凝固了，不会再变了，会一直保持这个结果。就算改变已经发生了，你再对<code>Promise</code>对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。</p>
<p>有了<code>Promise</code>对象，就可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。此外，<code>Promise</code>对象提供统一的接口，使得控制异步操作更加容易。</p>
<p><code>Promise</code>也有一些缺点。首先，无法取消<code>Promise</code>，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，<code>Promise</code>内部抛出的错误，不会反应到外部。第三，当处于<code>Pending</code>状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。</p>
<p>如果某些事件不断地反复发生，一般来说，使用stream模式是比部署<code>Promise</code>更好的选择。</p>
<h2 id="基本用法"><a href="#基本用法" class="headerlink" title="基本用法"></a>基本用法</h2><p>ES6规定，Promise对象是一个构造函数，用来生成Promise实例。</p>
<p>下面代码创造了一个Promise实例。</p>
<pre><code class="javascript"><span class="keyword">var</span> promise = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
  <span class="comment">// ... some code</span>

  <span class="keyword">if</span> (<span class="comment">/* 异步操作成功 */</span>){
    resolve(value);
  } <span class="keyword">else</span> {
    reject(error);
  }
});
</code></pre>
<p>Promise构造函数接受一个函数作为参数，该函数的两个参数分别是<code>resolve</code>和<code>reject</code>。它们是两个函数，由JavaScript引擎提供，不用自己部署。</p>
<p><code>resolve</code>函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从Pending变为Resolved），在异步操作成功时调用，并将异步操作的结果，作为参数传递出去；<code>reject</code>函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从Pending变为Rejected），在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。</p>
<p>Promise实例生成以后，可以用<code>then</code>方法分别指定<code>Resolved</code>状态和<code>Reject</code>状态的回调函数。</p>
<pre><code class="javascript">promise.then(<span class="function"><span class="keyword">function</span>(<span class="params">value</span>) </span>{
  <span class="comment">// success</span>
}, <span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="comment">// failure</span>
});
</code></pre>
<p><code>then</code>方法可以接受两个回调函数作为参数。第一个回调函数是Promise对象的状态变为Resolved时调用，第二个回调函数是Promise对象的状态变为Reject时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。</p>
<p>下面是一个Promise对象的简单例子。</p>
<pre><code class="javascript"><span class="function"><span class="keyword">function</span> <span class="title">timeout</span>(<span class="params">ms</span>) </span>{
  <span class="keyword">return</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function">(<span class="params">resolve, reject</span>) =&gt;</span> {
    setTimeout(resolve, ms, <span class="string">'done'</span>);
  });
}

timeout(<span class="number">100</span>).then(<span class="function">(<span class="params">value</span>) =&gt;</span> {
  <span class="built_in">console</span>.log(value);
});
</code></pre>
<p>上面代码中，<code>timeout</code>方法返回一个Promise实例，表示一段时间以后才会发生的结果。过了指定的时间（<code>ms</code>参数）以后，Promise实例的状态变为Resolved，就会触发<code>then</code>方法绑定的回调函数。</p>
<p>Promise新建后就会立即执行。</p>
<pre><code class="javascript"><span class="keyword">let</span> promise = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'Promise'</span>);
  resolve();
});

promise.then(<span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'Resolved.'</span>);
});

<span class="built_in">console</span>.log(<span class="string">'Hi!'</span>);

<span class="comment">// Promise</span>
<span class="comment">// Hi!</span>
<span class="comment">// Resolved</span>
</code></pre>
<p>上面代码中，Promise新建后立即执行，所以首先输出的是“Promise”。然后，<code>then</code>方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行，所以“Resolved”最后输出。</p>
<p>下面是异步加载图片的例子。</p>
<pre><code class="javascript"><span class="function"><span class="keyword">function</span> <span class="title">loadImageAsync</span>(<span class="params">url</span>) </span>{
  <span class="keyword">return</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
    <span class="keyword">var</span> image = <span class="keyword">new</span> Image();

    image.onload = <span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
      resolve(image);
    };

    image.onerror = <span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
      reject(<span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'Could not load image at '</span> + url));
    };

    image.src = url;
  });
}
</code></pre>
<p>上面代码中，使用Promise包装了一个图片加载的异步操作。如果加载成功，就调用<code>resolve</code>方法，否则就调用<code>reject</code>方法。</p>
<p>下面是一个用Promise对象实现的Ajax操作的例子。</p>
<pre><code class="javascript"><span class="keyword">var</span> getJSON = <span class="function"><span class="keyword">function</span>(<span class="params">url</span>) </span>{
  <span class="keyword">var</span> promise = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>)</span>{
    <span class="keyword">var</span> client = <span class="keyword">new</span> XMLHttpRequest();
    client.open(<span class="string">"GET"</span>, url);
    client.onreadystatechange = handler;
    client.responseType = <span class="string">"json"</span>;
    client.setRequestHeader(<span class="string">"Accept"</span>, <span class="string">"application/json"</span>);
    client.send();

    <span class="function"><span class="keyword">function</span> <span class="title">handler</span>(<span class="params"></span>) </span>{
      <span class="keyword">if</span> (<span class="keyword">this</span>.readyState !== <span class="number">4</span>) {
        <span class="keyword">return</span>;
      }
      <span class="keyword">if</span> (<span class="keyword">this</span>.status === <span class="number">200</span>) {
        resolve(<span class="keyword">this</span>.response);
      } <span class="keyword">else</span> {
        reject(<span class="keyword">new</span> <span class="built_in">Error</span>(<span class="keyword">this</span>.statusText));
      }
    };
  });

  <span class="keyword">return</span> promise;
};

getJSON(<span class="string">"/posts.json"</span>).then(<span class="function"><span class="keyword">function</span>(<span class="params">json</span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'Contents: '</span> + json);
}, <span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="built_in">console</span>.error(<span class="string">'出错了'</span>, error);
});
</code></pre>
<p>上面代码中，<code>getJSON</code>是对XMLHttpRequest对象的封装，用于发出一个针对JSON数据的HTTP请求，并且返回一个Promise对象。需要注意的是，在<code>getJSON</code>内部，<code>resolve</code>函数和<code>reject</code>函数调用时，都带有参数。</p>
<p>如果调用<code>resolve</code>函数和<code>reject</code>函数时带有参数，那么它们的参数会被传递给回调函数。<code>reject</code>函数的参数通常是Error对象的实例，表示抛出的错误；<code>resolve</code>函数的参数除了正常的值以外，还可能是另一个Promise实例，表示异步操作的结果有可能是一个值，也有可能是另一个异步操作，比如像下面这样。</p>
<pre><code class="javascript"><span class="keyword">var</span> p1 = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span> (<span class="params">resolve, reject</span>) </span>{
  <span class="comment">// ...</span>
});

<span class="keyword">var</span> p2 = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span> (<span class="params">resolve, reject</span>) </span>{
  <span class="comment">// ...</span>
  resolve(p1);
})
</code></pre>
<p>上面代码中，<code>p1</code>和<code>p2</code>都是Promise的实例，但是<code>p2</code>的<code>resolve</code>方法将<code>p1</code>作为参数，即一个异步操作的结果是返回另一个异步操作。</p>
<p>注意，这时<code>p1</code>的状态就会传递给<code>p2</code>，也就是说，<code>p1</code>的状态决定了<code>p2</code>的状态。如果<code>p1</code>的状态是<code>Pending</code>，那么<code>p2</code>的回调函数就会等待<code>p1</code>的状态改变；如果<code>p1</code>的状态已经是<code>Resolved</code>或者<code>Rejected</code>，那么<code>p2</code>的回调函数将会立刻执行。</p>
<pre><code class="javascript"><span class="keyword">var</span> p1 = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span> (<span class="params">resolve, reject</span>) </span>{
  setTimeout(<span class="function"><span class="params">()</span> =&gt;</span> reject(<span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'fail'</span>)), <span class="number">3000</span>)
})

<span class="keyword">var</span> p2 = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span> (<span class="params">resolve, reject</span>) </span>{
  setTimeout(<span class="function"><span class="params">()</span> =&gt;</span> resolve(p1), <span class="number">1000</span>)
})

p2
  .then(<span class="function"><span class="params">result</span> =&gt;</span> <span class="built_in">console</span>.log(result))
  .catch(<span class="function"><span class="params">error</span> =&gt;</span> <span class="built_in">console</span>.log(error))
<span class="comment">// Error: fail</span>
</code></pre>
<p>上面代码中，<code>p1</code>是一个Promise，3秒之后变为<code>rejected</code>。<code>p2</code>的状态在1秒之后改变，<code>resolve</code>方法返回的是<code>p1</code>。此时，由于<code>p2</code>返回的是另一个Promise，所以后面的<code>then</code>语句都变成针对后者（<code>p1</code>）。又过了2秒，<code>p1</code>变为<code>rejected</code>，导致触发<code>catch</code>方法指定的回调函数。</p>
<h2 id="Promise-prototype-then"><a href="#Promise-prototype-then" class="headerlink" title="Promise.prototype.then()"></a>Promise.prototype.then()</h2><p>Promise实例具有<code>then</code>方法，也就是说，<code>then</code>方法是定义在原型对象Promise.prototype上的。它的作用是为Promise实例添加状态改变时的回调函数。前面说过，<code>then</code>方法的第一个参数是Resolved状态的回调函数，第二个参数（可选）是Rejected状态的回调函数。</p>
<p><code>then</code>方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即<code>then</code>方法后面再调用另一个<code>then</code>方法。</p>
<pre><code class="javascript">getJSON(<span class="string">"/posts.json"</span>).then(<span class="function"><span class="keyword">function</span>(<span class="params">json</span>) </span>{
  <span class="keyword">return</span> json.post;
}).then(<span class="function"><span class="keyword">function</span>(<span class="params">post</span>) </span>{
  <span class="comment">// ...</span>
});
</code></pre>
<p>上面的代码使用<code>then</code>方法，依次指定了两个回调函数。第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数。</p>
<p>采用链式的<code>then</code>，可以指定一组按照次序调用的回调函数。这时，前一个回调函数，有可能返回的还是一个Promise对象（即有异步操作），这时后一个回调函数，就会等待该Promise对象的状态发生变化，才会被调用。</p>
<pre><code class="javascript">getJSON(<span class="string">"/post/1.json"</span>).then(<span class="function"><span class="keyword">function</span>(<span class="params">post</span>) </span>{
  <span class="keyword">return</span> getJSON(post.commentURL);
}).then(<span class="function"><span class="keyword">function</span> <span class="title">funcA</span>(<span class="params">comments</span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">"Resolved: "</span>, comments);
}, <span class="function"><span class="keyword">function</span> <span class="title">funcB</span>(<span class="params">err</span>)</span>{
  <span class="built_in">console</span>.log(<span class="string">"Rejected: "</span>, err);
});
</code></pre>
<p>上面代码中，第一个<code>then</code>方法指定的回调函数，返回的是另一个Promise对象。这时，第二个<code>then</code>方法指定的回调函数，就会等待这个新的Promise对象状态发生变化。如果变为Resolved，就调用<code>funcA</code>，如果状态变为Rejected，就调用<code>funcB</code>。</p>
<p>如果采用箭头函数，上面的代码可以写得更简洁。</p>
<pre><code class="javascript">getJSON(<span class="string">"/post/1.json"</span>).then(
  <span class="function"><span class="params">post</span> =&gt;</span> getJSON(post.commentURL)
).then(
  <span class="function"><span class="params">comments</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">"Resolved: "</span>, comments),
  err =&gt; <span class="built_in">console</span>.log(<span class="string">"Rejected: "</span>, err)
);
</code></pre>
<h2 id="Promise-prototype-catch"><a href="#Promise-prototype-catch" class="headerlink" title="Promise.prototype.catch()"></a>Promise.prototype.catch()</h2><p><code>Promise.prototype.catch</code>方法是<code>.then(null, rejection)</code>的别名，用于指定发生错误时的回调函数。</p>
<pre><code class="javascript">getJSON(<span class="string">"/posts.json"</span>).then(<span class="function"><span class="keyword">function</span>(<span class="params">posts</span>) </span>{
  <span class="comment">// ...</span>
}).catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="comment">// 处理 getJSON 和 前一个回调函数运行时发生的错误</span>
  <span class="built_in">console</span>.log(<span class="string">'发生错误！'</span>, error);
});
</code></pre>
<p>上面代码中，<code>getJSON</code>方法返回一个Promise对象，如果该对象状态变为<code>Resolved</code>，则会调用<code>then</code>方法指定的回调函数；如果异步操作抛出错误，状态就会变为<code>Rejected</code>，就会调用<code>catch</code>方法指定的回调函数，处理这个错误。另外，<code>then</code>方法指定的回调函数，如果运行中抛出错误，也会被<code>catch</code>方法捕获。</p>
<pre><code class="javascript">p.then(<span class="function">(<span class="params">val</span>) =&gt;</span> <span class="built_in">console</span>.log(<span class="string">"fulfilled:"</span>, val))
  .catch(<span class="function">(<span class="params">err</span>) =&gt;</span> <span class="built_in">console</span>.log(<span class="string">"rejected:"</span>, err));

<span class="comment">// 等同于</span>
p.then(<span class="function">(<span class="params">val</span>) =&gt;</span> <span class="built_in">console</span>.log(<span class="string">"fulfilled:"</span>, val))
  .then(<span class="literal">null</span>, (err) =&gt; <span class="built_in">console</span>.log(<span class="string">"rejected:"</span>, err));
</code></pre>
<p>下面是一个例子。</p>
<pre><code class="javascript"><span class="keyword">var</span> promise = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
  <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'test'</span>);
});
promise.catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="built_in">console</span>.log(error);
});
<span class="comment">// Error: test</span>
</code></pre>
<p>上面代码中，<code>promise</code>抛出一个错误，就被<code>catch</code>方法指定的回调函数捕获。注意，上面的写法与下面两种写法是等价的。</p>
<pre><code class="javascript"><span class="comment">// 写法一</span>
<span class="keyword">var</span> promise = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
  <span class="keyword">try</span> {
    <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'test'</span>);
  } <span class="keyword">catch</span>(e) {
    reject(e);
  }
});
promise.catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="built_in">console</span>.log(error);
});

<span class="comment">// 写法二</span>
<span class="keyword">var</span> promise = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
  reject(<span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'test'</span>));
});
promise.catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="built_in">console</span>.log(error);
});
</code></pre>
<p>比较上面两种写法，可以发现<code>reject</code>方法的作用，等同于抛出错误。</p>
<p>如果Promise状态已经变成<code>Resolved</code>，再抛出错误是无效的。</p>
<pre><code class="javascript"><span class="keyword">var</span> promise = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
  resolve(<span class="string">'ok'</span>);
  <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'test'</span>);
});
promise
  .then(<span class="function"><span class="keyword">function</span>(<span class="params">value</span>) </span>{ <span class="built_in">console</span>.log(value) })
  .catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{ <span class="built_in">console</span>.log(error) });
<span class="comment">// ok</span>
</code></pre>
<p>上面代码中，Promise在<code>resolve</code>语句后面，再抛出错误，不会被捕获，等于没有抛出。</p>
<p>Promise对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个<code>catch</code>语句捕获。</p>
<pre><code class="javascript">getJSON(<span class="string">"/post/1.json"</span>).then(<span class="function"><span class="keyword">function</span>(<span class="params">post</span>) </span>{
  <span class="keyword">return</span> getJSON(post.commentURL);
}).then(<span class="function"><span class="keyword">function</span>(<span class="params">comments</span>) </span>{
  <span class="comment">// some code</span>
}).catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="comment">// 处理前面三个Promise产生的错误</span>
});
</code></pre>
<p>上面代码中，一共有三个Promise对象：一个由<code>getJSON</code>产生，两个由<code>then</code>产生。它们之中任何一个抛出的错误，都会被最后一个<code>catch</code>捕获。</p>
<p>一般来说，不要在<code>then</code>方法里面定义Reject状态的回调函数（即<code>then</code>的第二个参数），总是使用<code>catch</code>方法。</p>
<pre><code class="javascript"><span class="comment">// bad</span>
promise
  .then(<span class="function"><span class="keyword">function</span>(<span class="params">data</span>) </span>{
    <span class="comment">// success</span>
  }, <span class="function"><span class="keyword">function</span>(<span class="params">err</span>) </span>{
    <span class="comment">// error</span>
  });

<span class="comment">// good</span>
promise
  .then(<span class="function"><span class="keyword">function</span>(<span class="params">data</span>) </span>{ <span class="comment">//cb</span>
    <span class="comment">// success</span>
  })
  .catch(<span class="function"><span class="keyword">function</span>(<span class="params">err</span>) </span>{
    <span class="comment">// error</span>
  });
</code></pre>
<p>上面代码中，第二种写法要好于第一种写法，理由是第二种写法可以捕获前面<code>then</code>方法执行中的错误，也更接近同步的写法（<code>try/catch</code>）。因此，建议总是使用<code>catch</code>方法，而不使用<code>then</code>方法的第二个参数。</p>
<p>跟传统的<code>try/catch</code>代码块不同的是，如果没有使用<code>catch</code>方法指定错误处理的回调函数，Promise对象抛出的错误不会传递到外层代码，即不会有任何反应。</p>
<pre><code class="javascript"><span class="keyword">var</span> someAsyncThing = <span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="keyword">return</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
    <span class="comment">// 下面一行会报错，因为x没有声明</span>
    resolve(x + <span class="number">2</span>);
  });
};

someAsyncThing().then(<span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'everything is great'</span>);
});
</code></pre>
<p>上面代码中，<code>someAsyncThing</code>函数产生的Promise对象会报错，但是由于没有指定<code>catch</code>方法，这个错误不会被捕获，也不会传递到外层代码，导致运行后没有任何输出。注意，Chrome浏览器不遵守这条规定，它会抛出错误“ReferenceError: x is not defined”。</p>
<pre><code class="javascript"><span class="keyword">var</span> promise = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
  resolve(<span class="string">'ok'</span>);
  setTimeout(<span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{ <span class="keyword">throw</span> <span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'test'</span>) }, <span class="number">0</span>)
});
promise.then(<span class="function"><span class="keyword">function</span>(<span class="params">value</span>) </span>{ <span class="built_in">console</span>.log(value) });
<span class="comment">// ok</span>
<span class="comment">// Uncaught Error: test</span>
</code></pre>
<p>上面代码中，Promise 指定在下一轮“事件循环”再抛出错误，结果由于没有指定使用<code>try...catch</code>语句，就冒泡到最外层，成了未捕获的错误。因为此时，Promise的函数体已经运行结束了，所以这个错误是在Promise函数体外抛出的。</p>
<p>Node 有一个<code>unhandledRejection</code>事件，专门监听未捕获的<code>reject</code>错误。</p>
<pre><code class="javascript">process.on(<span class="string">'unhandledRejection'</span>, <span class="function"><span class="keyword">function</span> (<span class="params">err, p</span>) </span>{
  <span class="built_in">console</span>.error(err.stack)
});
</code></pre>
<p>上面代码中，<code>unhandledRejection</code>事件的监听函数有两个参数，第一个是错误对象，第二个是报错的Promise实例，它可以用来了解发生错误的环境信息。。</p>
<p>需要注意的是，<code>catch</code>方法返回的还是一个 Promise 对象，因此后面还可以接着调用<code>then</code>方法。</p>
<pre><code class="javascript"><span class="keyword">var</span> someAsyncThing = <span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="keyword">return</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
    <span class="comment">// 下面一行会报错，因为x没有声明</span>
    resolve(x + <span class="number">2</span>);
  });
};

someAsyncThing()
.catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'oh no'</span>, error);
})
.then(<span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'carry on'</span>);
});
<span class="comment">// oh no [ReferenceError: x is not defined]</span>
<span class="comment">// carry on</span>
</code></pre>
<p>上面代码运行完<code>catch</code>方法指定的回调函数，会接着运行后面那个<code>then</code>方法指定的回调函数。如果没有报错，则会跳过<code>catch</code>方法。</p>
<pre><code class="javascript"><span class="built_in">Promise</span>.resolve()
.catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'oh no'</span>, error);
})
.then(<span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'carry on'</span>);
});
<span class="comment">// carry on</span>
</code></pre>
<p>上面的代码因为没有报错，跳过了<code>catch</code>方法，直接执行后面的<code>then</code>方法。此时，要是<code>then</code>方法里面报错，就与前面的<code>catch</code>无关了。</p>
<p><code>catch</code>方法之中，还能再抛出错误。</p>
<pre><code class="javascript"><span class="keyword">var</span> someAsyncThing = <span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="keyword">return</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
    <span class="comment">// 下面一行会报错，因为x没有声明</span>
    resolve(x + <span class="number">2</span>);
  });
};

someAsyncThing().then(<span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="keyword">return</span> someOtherAsyncThing();
}).catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'oh no'</span>, error);
  <span class="comment">// 下面一行会报错，因为y没有声明</span>
  y + <span class="number">2</span>;
}).then(<span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'carry on'</span>);
});
<span class="comment">// oh no [ReferenceError: x is not defined]</span>
</code></pre>
<p>上面代码中，<code>catch</code>方法抛出一个错误，因为后面没有别的<code>catch</code>方法了，导致这个错误不会被捕获，也不会传递到外层。如果改写一下，结果就不一样了。</p>
<pre><code class="javascript">someAsyncThing().then(<span class="function"><span class="keyword">function</span>(<span class="params"></span>) </span>{
  <span class="keyword">return</span> someOtherAsyncThing();
}).catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'oh no'</span>, error);
  <span class="comment">// 下面一行会报错，因为y没有声明</span>
  y + <span class="number">2</span>;
}).catch(<span class="function"><span class="keyword">function</span>(<span class="params">error</span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'carry on'</span>, error);
});
<span class="comment">// oh no [ReferenceError: x is not defined]</span>
<span class="comment">// carry on [ReferenceError: y is not defined]</span>
</code></pre>
<p>上面代码中，第二个<code>catch</code>方法用来捕获，前一个<code>catch</code>方法抛出的错误。</p>
<h2 id="Promise-all"><a href="#Promise-all" class="headerlink" title="Promise.all()"></a>Promise.all()</h2><p><code>Promise.all</code>方法用于将多个Promise实例，包装成一个新的Promise实例。</p>
<pre><code class="javascript"><span class="keyword">var</span> p = <span class="built_in">Promise</span>.all([p1, p2, p3]);
</code></pre>
<p>上面代码中，<code>Promise.all</code>方法接受一个数组作为参数，<code>p1</code>、<code>p2</code>、<code>p3</code>都是Promise对象的实例，如果不是，就会先调用下面讲到的<code>Promise.resolve</code>方法，将参数转为Promise实例，再进一步处理。（<code>Promise.all</code>方法的参数可以不是数组，但必须具有Iterator接口，且返回的每个成员都是Promise实例。）</p>
<p><code>p</code>的状态由<code>p1</code>、<code>p2</code>、<code>p3</code>决定，分成两种情况。</p>
<p>（1）只有<code>p1</code>、<code>p2</code>、<code>p3</code>的状态都变成<code>fulfilled</code>，<code>p</code>的状态才会变成<code>fulfilled</code>，此时<code>p1</code>、<code>p2</code>、<code>p3</code>的返回值组成一个数组，传递给<code>p</code>的回调函数。</p>
<p>（2）只要<code>p1</code>、<code>p2</code>、<code>p3</code>之中有一个被<code>rejected</code>，<code>p</code>的状态就变成<code>rejected</code>，此时第一个被<code>reject</code>的实例的返回值，会传递给<code>p</code>的回调函数。</p>
<p>下面是一个具体的例子。</p>
<pre><code class="javascript"><span class="comment">// 生成一个Promise对象的数组</span>
<span class="keyword">var</span> promises = [<span class="number">2</span>, <span class="number">3</span>, <span class="number">5</span>, <span class="number">7</span>, <span class="number">11</span>, <span class="number">13</span>].map(<span class="function"><span class="keyword">function</span> (<span class="params">id</span>) </span>{
  <span class="keyword">return</span> getJSON(<span class="string">"/post/"</span> + id + <span class="string">".json"</span>);
});

<span class="built_in">Promise</span>.all(promises).then(<span class="function"><span class="keyword">function</span> (<span class="params">posts</span>) </span>{
  <span class="comment">// ...</span>
}).catch(<span class="function"><span class="keyword">function</span>(<span class="params">reason</span>)</span>{
  <span class="comment">// ...</span>
});
</code></pre>
<p>上面代码中，<code>promises</code>是包含6个Promise实例的数组，只有这6个实例的状态都变成<code>fulfilled</code>，或者其中有一个变为<code>rejected</code>，才会调用<code>Promise.all</code>方法后面的回调函数。</p>
<p>下面是另一个例子。</p>
<pre><code class="javascript"><span class="keyword">const</span> databasePromise = connectDatabase();

<span class="keyword">const</span> booksPromise = databaseProimse
  .then(findAllBooks);

<span class="keyword">const</span> userPromise = databasePromise
  .then(getCurrentUser);

<span class="built_in">Promise</span>.all([
  booksPromise,
  userPromise
])
.then(<span class="function">(<span class="params">[books, user]</span>) =&gt;</span> pickTopRecommentations(books, user));
</code></pre>
<p>上面代码中，<code>booksPromise</code>和<code>userPromise</code>是两个异步操作，只有等到它们的结果都返回了，才会触发<code>pickTopRecommentations</code>这个回调函数。</p>
<h2 id="Promise-race"><a href="#Promise-race" class="headerlink" title="Promise.race()"></a>Promise.race()</h2><p><code>Promise.race</code>方法同样是将多个Promise实例，包装成一个新的Promise实例。</p>
<pre><code class="javascript"><span class="keyword">var</span> p = <span class="built_in">Promise</span>.race([p1, p2, p3]);
</code></pre>
<p>上面代码中，只要<code>p1</code>、<code>p2</code>、<code>p3</code>之中有一个实例率先改变状态，<code>p</code>的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给<code>p</code>的回调函数。</p>
<p><code>Promise.race</code>方法的参数与<code>Promise.all</code>方法一样，如果不是 Promise 实例，就会先调用下面讲到的<code>Promise.resolve</code>方法，将参数转为 Promise 实例，再进一步处理。</p>
<p>下面是一个例子，如果指定时间内没有获得结果，就将Promise的状态变为<code>reject</code>，否则变为<code>resolve</code>。</p>
<pre><code class="javascript"><span class="keyword">var</span> p = <span class="built_in">Promise</span>.race([
  fetch(<span class="string">'/resource-that-may-take-a-while'</span>),
  <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span> (<span class="params">resolve, reject</span>) </span>{
    setTimeout(<span class="function"><span class="params">()</span> =&gt;</span> reject(<span class="keyword">new</span> <span class="built_in">Error</span>(<span class="string">'request timeout'</span>)), <span class="number">5000</span>)
  })
])
p.then(<span class="function"><span class="params">response</span> =&gt;</span> <span class="built_in">console</span>.log(response))
p.catch(<span class="function"><span class="params">error</span> =&gt;</span> <span class="built_in">console</span>.log(error))
</code></pre>
<p>上面代码中，如果5秒之内<code>fetch</code>方法无法返回结果，变量<code>p</code>的状态就会变为<code>rejected</code>，从而触发<code>catch</code>方法指定的回调函数。</p>
<h2 id="Promise-resolve"><a href="#Promise-resolve" class="headerlink" title="Promise.resolve()"></a>Promise.resolve()</h2><p>有时需要将现有对象转为Promise对象，<code>Promise.resolve</code>方法就起到这个作用。</p>
<pre><code class="javascript"><span class="keyword">var</span> jsPromise = <span class="built_in">Promise</span>.resolve($.ajax(<span class="string">'/whatever.json'</span>));
</code></pre>
<p>上面代码将jQuery生成的<code>deferred</code>对象，转为一个新的Promise对象。</p>
<p><code>Promise.resolve</code>等价于下面的写法。</p>
<pre><code class="javascript"><span class="built_in">Promise</span>.resolve(<span class="string">'foo'</span>)
<span class="comment">// 等价于</span>
<span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="params">resolve</span> =&gt;</span> resolve(<span class="string">'foo'</span>))
</code></pre>
<p><code>Promise.resolve</code>方法的参数分成四种情况。</p>
<p><strong>（1）参数是一个Promise实例</strong></p>
<p>如果参数是Promise实例，那么<code>Promise.resolve</code>将不做任何修改、原封不动地返回这个实例。</p>
<p><strong>（2）参数是一个<code>thenable</code>对象</strong></p>
<p><code>thenable</code>对象指的是具有<code>then</code>方法的对象，比如下面这个对象。</p>
<pre><code class="javascript"><span class="keyword">let</span> thenable = {
  <span class="attr">then</span>: <span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
    resolve(<span class="number">42</span>);
  }
};
</code></pre>
<p><code>Promise.resolve</code>方法会将这个对象转为Promise对象，然后就立即执行<code>thenable</code>对象的<code>then</code>方法。</p>
<pre><code class="javascript"><span class="keyword">let</span> thenable = {
  <span class="attr">then</span>: <span class="function"><span class="keyword">function</span>(<span class="params">resolve, reject</span>) </span>{
    resolve(<span class="number">42</span>);
  }
};

<span class="keyword">let</span> p1 = <span class="built_in">Promise</span>.resolve(thenable);
p1.then(<span class="function"><span class="keyword">function</span>(<span class="params">value</span>) </span>{
  <span class="built_in">console</span>.log(value);  <span class="comment">// 42</span>
});
</code></pre>
<p>上面代码中，<code>thenable</code>对象的<code>then</code>方法执行后，对象<code>p1</code>的状态就变为<code>resolved</code>，从而立即执行最后那个<code>then</code>方法指定的回调函数，输出42。</p>
<p><strong>（3）参数不是具有<code>then</code>方法的对象，或根本就不是对象</strong></p>
<p>如果参数是一个原始值，或者是一个不具有<code>then</code>方法的对象，则<code>Promise.resolve</code>方法返回一个新的Promise对象，状态为<code>Resolved</code>。</p>
<pre><code class="javascript"><span class="keyword">var</span> p = <span class="built_in">Promise</span>.resolve(<span class="string">'Hello'</span>);

p.then(<span class="function"><span class="keyword">function</span> (<span class="params">s</span>)</span>{
  <span class="built_in">console</span>.log(s)
});
<span class="comment">// Hello</span>
</code></pre>
<p>上面代码生成一个新的Promise对象的实例<code>p</code>。由于字符串<code>Hello</code>不属于异步操作（判断方法是它不是具有then方法的对象），返回Promise实例的状态从一生成就是<code>Resolved</code>，所以回调函数会立即执行。<code>Promise.resolve</code>方法的参数，会同时传给回调函数。</p>
<p><strong>（4）不带有任何参数</strong></p>
<p><code>Promise.resolve</code>方法允许调用时不带参数，直接返回一个<code>Resolved</code>状态的Promise对象。</p>
<p>所以，如果希望得到一个Promise对象，比较方便的方法就是直接调用<code>Promise.resolve</code>方法。</p>
<pre><code class="javascript"><span class="keyword">var</span> p = <span class="built_in">Promise</span>.resolve();

p.then(<span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>{
  <span class="comment">// ...</span>
});
</code></pre>
<p>上面代码的变量<code>p</code>就是一个Promise对象。</p>
<p>需要注意的是，立即<code>resolve</code>的Promise对象，是在本轮“事件循环”（event loop）的结束时，而不是在下一轮“事件循环”的开始时。</p>
<pre><code class="javascript">setTimeout(<span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'three'</span>);
}, <span class="number">0</span>);

<span class="built_in">Promise</span>.resolve().then(<span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>{
  <span class="built_in">console</span>.log(<span class="string">'two'</span>);
});

<span class="built_in">console</span>.log(<span class="string">'one'</span>);

<span class="comment">// one</span>
<span class="comment">// two</span>
<span class="comment">// three</span>
</code></pre>
<p>上面代码中，<code>setTimeout(fn, 0)</code>在下一轮“事件循环”开始时执行，<code>Promise.resolve()</code>在本轮“事件循环”结束时执行，<code>console.log(’one‘)</code>则是立即执行，因此最先输出。</p>
<h2 id="Promise-reject"><a href="#Promise-reject" class="headerlink" title="Promise.reject()"></a>Promise.reject()</h2><p><code>Promise.reject(reason)</code>方法也会返回一个新的 Promise 实例，该实例的状态为<code>rejected</code>。</p>
<pre><code class="javascript"><span class="keyword">var</span> p = <span class="built_in">Promise</span>.reject(<span class="string">'出错了'</span>);
<span class="comment">// 等同于</span>
<span class="keyword">var</span> p = <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function">(<span class="params">resolve, reject</span>) =&gt;</span> reject(<span class="string">'出错了'</span>))

p.then(<span class="literal">null</span>, <span class="function"><span class="keyword">function</span> (<span class="params">s</span>) </span>{
  <span class="built_in">console</span>.log(s)
});
<span class="comment">// 出错了</span>
</code></pre>
<p>上面代码生成一个Promise对象的实例<code>p</code>，状态为<code>rejected</code>，回调函数会立即执行。</p>
<p>注意，<code>Promise.reject()</code>方法的参数，会原封不动地作为<code>reject</code>的理由，变成后续方法的参数。这一点与<code>Promise.resolve</code>方法不一致。</p>
<pre><code class="javascript"><span class="keyword">const</span> thenable = {
  then(resolve, reject) {
    reject(<span class="string">'出错了'</span>);
  }
};

<span class="built_in">Promise</span>.reject(thenable)
.catch(<span class="function"><span class="params">e</span> =&gt;</span> {
  <span class="built_in">console</span>.log(e === thenable)
})
<span class="comment">// true</span>
</code></pre>
<p>上面代码中，<code>Promise.reject</code>方法的参数是一个<code>thenable</code>对象，执行以后，后面<code>catch</code>方法的参数不是<code>reject</code>抛出的“出错了”这个字符串，而是<code>thenable</code>对象。</p>
<h2 id="两个有用的附加方法"><a href="#两个有用的附加方法" class="headerlink" title="两个有用的附加方法"></a>两个有用的附加方法</h2><p>ES6的Promise API提供的方法不是很多，有些有用的方法可以自己部署。下面介绍如何部署两个不在ES6之中、但很有用的方法。</p>
<h3 id="done"><a href="#done" class="headerlink" title="done()"></a>done()</h3><p>Promise对象的回调链，不管以<code>then</code>方法或<code>catch</code>方法结尾，要是最后一个方法抛出错误，都有可能无法捕捉到（因为Promise内部的错误不会冒泡到全局）。因此，我们可以提供一个<code>done</code>方法，总是处于回调链的尾端，保证抛出任何可能出现的错误。</p>
<pre><code class="javascript">asyncFunc()
  .then(f1)
  .catch(r1)
  .then(f2)
  .done();
</code></pre>
<p>它的实现代码相当简单。</p>
<pre><code class="javascript"><span class="built_in">Promise</span>.prototype.done = <span class="function"><span class="keyword">function</span> (<span class="params">onFulfilled, onRejected</span>) </span>{
  <span class="keyword">this</span>.then(onFulfilled, onRejected)
    .catch(<span class="function"><span class="keyword">function</span> (<span class="params">reason</span>) </span>{
      <span class="comment">// 抛出一个全局错误</span>
      setTimeout(<span class="function"><span class="params">()</span> =&gt;</span> { <span class="keyword">throw</span> reason }, <span class="number">0</span>);
    });
};
</code></pre>
<p>从上面代码可见，<code>done</code>方法的使用，可以像<code>then</code>方法那样用，提供<code>Fulfilled</code>和<code>Rejected</code>状态的回调函数，也可以不提供任何参数。但不管怎样，<code>done</code>都会捕捉到任何可能出现的错误，并向全局抛出。</p>
<h3 id="finally"><a href="#finally" class="headerlink" title="finally()"></a>finally()</h3><p><code>finally</code>方法用于指定不管Promise对象最后状态如何，都会执行的操作。它与<code>done</code>方法的最大区别，它接受一个普通的回调函数作为参数，该函数不管怎样都必须执行。</p>
<p>下面是一个例子，服务器使用Promise处理请求，然后使用<code>finally</code>方法关掉服务器。</p>
<pre><code class="javascript">server.listen(<span class="number">0</span>)
  .then(<span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>{
    <span class="comment">// run test</span>
  })
  .finally(server.stop);
</code></pre>
<p>它的实现也很简单。</p>
<pre><code class="javascript"><span class="built_in">Promise</span>.prototype.finally = <span class="function"><span class="keyword">function</span> (<span class="params">callback</span>) </span>{
  <span class="keyword">let</span> P = <span class="keyword">this</span>.constructor;
  <span class="keyword">return</span> <span class="keyword">this</span>.then(
    <span class="function"><span class="params">value</span>  =&gt;</span> P.resolve(callback()).then(<span class="function"><span class="params">()</span> =&gt;</span> value),
    reason =&gt; P.resolve(callback()).then(<span class="function"><span class="params">()</span> =&gt;</span> { <span class="keyword">throw</span> reason })
  );
};
</code></pre>
<p>上面代码中，不管前面的Promise是<code>fulfilled</code>还是<code>rejected</code>，都会执行回调函数<code>callback</code>。</p>
<p>更多IT技术分享尽在 🔗<a href="http://microzz.com" target="_blank" rel="external">涵月天-microzz.com</a></p>
<h2 id="应用"><a href="#应用" class="headerlink" title="应用"></a>应用</h2><h3 id="加载图片"><a href="#加载图片" class="headerlink" title="加载图片"></a>加载图片</h3><p>我们可以将图片的加载写成一个<code>Promise</code>，一旦加载完成，<code>Promise</code>的状态就发生变化。</p>
<pre><code class="javascript"><span class="keyword">const</span> preloadImage = <span class="function"><span class="keyword">function</span> (<span class="params">path</span>) </span>{
  <span class="keyword">return</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span> (<span class="params">resolve, reject</span>) </span>{
    <span class="keyword">var</span> image = <span class="keyword">new</span> Image();
    image.onload  = resolve;
    image.onerror = reject;
    image.src = path;
  });
};
</code></pre>
<h3 id="Generator函数与Promise的结合"><a href="#Generator函数与Promise的结合" class="headerlink" title="Generator函数与Promise的结合"></a>Generator函数与Promise的结合</h3><p>使用Generator函数管理流程，遇到异步操作的时候，通常返回一个<code>Promise</code>对象。</p>
<pre><code class="javascript"><span class="function"><span class="keyword">function</span> <span class="title">getFoo</span> (<span class="params"></span>) </span>{
  <span class="keyword">return</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(<span class="function"><span class="keyword">function</span> (<span class="params">resolve, reject</span>)</span>{
    resolve(<span class="string">'foo'</span>);
  });
}

<span class="keyword">var</span> g = <span class="function"><span class="keyword">function</span>* (<span class="params"></span>) </span>{
  <span class="keyword">try</span> {
    <span class="keyword">var</span> foo = <span class="keyword">yield</span> getFoo();
    <span class="built_in">console</span>.log(foo);
  } <span class="keyword">catch</span> (e) {
    <span class="built_in">console</span>.log(e);
  }
};

<span class="function"><span class="keyword">function</span> <span class="title">run</span> (<span class="params">generator</span>) </span>{
  <span class="keyword">var</span> it = generator();

  <span class="function"><span class="keyword">function</span> <span class="title">go</span>(<span class="params">result</span>) </span>{
    <span class="keyword">if</span> (result.done) <span class="keyword">return</span> result.value;

    <span class="keyword">return</span> result.value.then(<span class="function"><span class="keyword">function</span> (<span class="params">value</span>) </span>{
      <span class="keyword">return</span> go(it.next(value));
    }, <span class="function"><span class="keyword">function</span> (<span class="params">error</span>) </span>{
      <span class="keyword">return</span> go(it.throw(error));
    });
  }

  go(it.next());
}

run(g);
</code></pre>
<p>上面代码的Generator函数<code>g</code>之中，有一个异步操作<code>getFoo</code>，它返回的就是一个<code>Promise</code>对象。函数<code>run</code>用来处理这个<code>Promise</code>对象，并调用下一个<code>next</code>方法。</p>
<h2 id="Promise-try"><a href="#Promise-try" class="headerlink" title="Promise.try()"></a>Promise.try()</h2><p>实际开发中，经常遇到一种情况：不知道或者不想区分，函数<code>f</code>是同步函数还是异步操作，但是想用 Promise 来处理它。因为这样就可以不管<code>f</code>是否包含异步操作，都用<code>then</code>方法指定下一步流程，用<code>catch</code>方法处理<code>f</code>抛出的错误。一般就会采用下面的写法。</p>
<pre><code class="javascript"><span class="built_in">Promise</span>.resolve().then(f)
</code></pre>
<p>上面的写法有一个缺点，就是如果<code>f</code>是同步函数，那么它会在本轮事件循环的末尾执行。</p>
<pre><code class="javascript"><span class="keyword">const</span> f = <span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">'now'</span>);
<span class="built_in">Promise</span>.resolve().then(f);
<span class="built_in">console</span>.log(<span class="string">'next'</span>);
<span class="comment">// next</span>
<span class="comment">// now</span>
</code></pre>
<p>上面代码中，函数<code>f</code>是同步的，但是用 Promise 包装了以后，就变成异步执行了。</p>
<p>那么有没有一种方法，让同步函数同步执行，异步函数异步执行，并且让它们具有统一的 API 呢？回答是可以的，并且还有两种写法。第一种写法是用<code>async</code>函数来写。</p>
<pre><code class="javascript"><span class="keyword">const</span> f = <span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">'now'</span>);
<span class="function">(<span class="params"><span class="keyword">async</span> (</span>) =&gt;</span> f())();
<span class="built_in">console</span>.log(<span class="string">'next'</span>);
<span class="comment">// now</span>
<span class="comment">// next</span>
</code></pre>
<p>上面代码中，第二行是一个立即执行的匿名函数，会立即执行里面的<code>async</code>函数，因此如果<code>f</code>是同步的，就会得到同步的结果；如果<code>f</code>是异步的，就可以用<code>then</code>指定下一步，就像下面的写法。</p>
<pre><code class="javascript">(<span class="keyword">async</span> () =&gt; f())()
.then(...)
</code></pre>
<p>需要注意的是，<code>async () =&gt; f()</code>会吃掉<code>f()</code>抛出的错误。所以，如果想捕获错误，要使用<code>promise.catch</code>方法。</p>
<pre><code class="javascript">(<span class="keyword">async</span> () =&gt; f())()
.then(...)
.catch(...)
</code></pre>
<p>第二种写法是使用<code>new Promise()</code>。</p>
<pre><code class="javascript"><span class="keyword">const</span> f = <span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">'now'</span>);
(
  <span class="function"><span class="params">()</span> =&gt;</span> <span class="keyword">new</span> <span class="built_in">Promise</span>(
    <span class="function"><span class="params">resolve</span> =&gt;</span> resolve(f())
  )
)();
<span class="built_in">console</span>.log(<span class="string">'next'</span>);
<span class="comment">// now</span>
<span class="comment">// next</span>
</code></pre>
<p>上面代码也是使用立即执行的匿名函数，执行<code>new Promise()</code>。这种情况下，同步函数也是同步执行的。</p>
<p>鉴于这是一个很常见的需求，所以现在有一个<a href="https://github.com/ljharb/proposal-promise-try" target="_blank" rel="external">提案</a>，提供<code>Promise.try</code>方法替代上面的写法。</p>
<pre><code class="javascript"><span class="keyword">const</span> f = <span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">'now'</span>);
<span class="built_in">Promise</span>.try(f);
<span class="built_in">console</span>.log(<span class="string">'next'</span>);
<span class="comment">// now</span>
<span class="comment">// next</span>
</code></pre>
<p>事实上，<code>Promise.try</code>存在已久，Promise 库<a href="http://bluebirdjs.com/docs/api/promise.try.html" target="_blank" rel="external"><code>Bluebird</code></a>、<a href="https://github.com/kriskowal/q/wiki/API-Reference#promisefcallargs" target="_blank" rel="external"><code>Q</code></a>和<a href="https://github.com/cujojs/when/blob/master/docs/api.md#whentry" target="_blank" rel="external"><code>when</code></a>，早就提供了这个方法。</p>
<p>由于<code>Promise.try</code>为所有操作提供了统一的处理机制，所以如果想用<code>then</code>方法管理流程，最好都用<code>Promise.try</code>包装一下。这样有<a href="http://cryto.net/~joepie91/blog/2016/05/11/what-is-promise-try-and-why-does-it-matter/" target="_blank" rel="external">许多好处</a>，其中一点就是可以更好地管理异常。</p>
<pre><code class="javascript"><span class="function"><span class="keyword">function</span> <span class="title">getUsername</span>(<span class="params">userId</span>) </span>{
  <span class="keyword">return</span> database.users.get({<span class="attr">id</span>: userId})
  .then(<span class="function"><span class="keyword">function</span>(<span class="params">user</span>) </span>{
    <span class="keyword">return</span> user.name;
  });
}
</code></pre>
<p>上面代码中，<code>database.users.get()</code>返回一个 Promise 对象，如果抛出异步错误，可以用<code>catch</code>方法捕获，就像下面这样写。</p>
<pre><code class="javascript">database.users.get({<span class="attr">id</span>: userId})
.then(...)
.catch(...)
</code></pre>
<p>但是<code>database.users.get()</code>可能还会抛出同步错误（比如数据库连接错误，具体要看实现方法），这时你就不得不用<code>try...catch</code>去捕获。</p>
<pre><code class="javascript"><span class="keyword">try</span> {
  database.users.get({<span class="attr">id</span>: userId})
  .then(...)
  .catch(...)
} <span class="keyword">catch</span> (e) {
  <span class="comment">// ...</span>
}
</code></pre>
<p>上面这样的写法就很笨拙了，这时就可以统一用<code>promise.catch()</code>捕获所有同步和异步的错误。</p>
<pre><code class="javascript"><span class="built_in">Promise</span>.try(database.users.get({<span class="attr">id</span>: userId}))
  .then(...)
  .catch(...)
</code></pre>
<p>事实上，<code>Promise.try</code>就是模拟<code>try</code>代码块，就像<code>promise.catch</code>模拟的是<code>catch</code>代码块。</p>
</div></header></article><section class="reward"> <a href="#" class="btn-reward">打赏</a><div class="reward-wrapper clearfix"><img src="/img/wechat.png"></div></section></main><footer class="foot"><div class="foot-copy u-fl">&copy; 2016-2017 microzz</div><menu class="page-menu u-fr"><li class="page-menu__item"><a title="Previous" href="/2017/04/19/operator/" class="page-menu__link icon-arrow-left"></a></li><li class="page-menu__item"><a title="Next" href="/2017/04/19/proxy/" class="page-menu__link icon-arrow-right"></a></li></menu></footer><script src="/js/scroller.js"></script><script src="/js/main.js"></script></body></html>